"""HTML email shell that applies tenant branding."""
from __future__ import annotations

import re

from branding import Branding

NEGATIVE_HINTS = (
    "cancel",
    "reject",
    "denied",
    "fail",
    "error",
    "revoke",
    "remov",
    "expir",
    "violat",
    "block",
    "suspend",
    "annul",
    "refus",
    "échou",
    "erreur",
)


def looks_negative(key: str, name: str = "", subject: str = "") -> bool:
    blob = f"{key} {name} {subject}".lower()
    return any(h in blob for h in NEGATIVE_HINTS)


def strip_existing_shell(body: str) -> str:
    """If body is already our branded table, return the inner content cell."""
    if not body:
        return ""
    content_cell = re.search(
        r'<td style="padding: ?30px 25px;?[^"]*">(.*?)</td>\s*</tr>\s*'
        r'<tr[^>]*>\s*<td style="background-color',
        body,
        flags=re.S,
    )
    if content_cell:
        return content_cell.group(1).strip()
    m = re.search(
        r"<img[^>]+(?:Logo|logo)[^>]*>.*?</td>\s*</tr>\s*<tr>\s*<td[^>]*>(.*)</td>\s*</tr>\s*<tr>\s*<td[^>]*>.*?e-mail automatique",
        body,
        flags=re.I | re.S,
    )
    if m:
        return m.group(1).strip()
    if 'border: 1px solid #cccccc' in body and 'e-mail automatique' in body:
        inner = re.sub(r'^.*?<td style="padding: 30px 25px;">', "", body, count=1, flags=re.S)
        inner = re.sub(
            r"</td>\s*</tr>\s*<tr>\s*<td style=\"padding: 15px; text-align: center;.*$",
            "",
            inner,
            count=1,
            flags=re.S,
        )
        return inner.strip()
    return body.strip()


LOGO_CELL_STYLE = "padding: 20px 0 20px 20px;"
_PREVIOUS_LOGO_CELL = '<td style="padding: 20px 0;">'
_CURRENT_LOGO_CELL = f'<td style="{LOGO_CELL_STYLE}">'


def pad_logo_cell(body: str) -> str:
    """Inset the logo from the left frame by the same amount as from the top."""
    return body.replace(_PREVIOUS_LOGO_CELL, _CURRENT_LOGO_CELL, 1)


def wrap_body(
    branding: Branding,
    inner_html: str,
    *,
    title: str | None = None,
    negative: bool = False,
    language: str = "en",
) -> str:
    title_color = branding.title_color(negative=negative)
    title_html = ""
    if title:
        title_html = (
            f'<h2 style="color:{title_color};margin:0 0 20px 0">{_escape_title(title)}</h2>'
        )
    footer = _footer_text(language, branding.product_name)
    return (
        '<table style="border-collapse: collapse; border: 1px solid #cccccc; '
        'margin-top: 20px; background-color: #ffffff;">'
        "<tbody>"
        f'<tr><td style="background-color: {branding.navigation_color}; height: 8px; '
        'font-size: 0; line-height: 0;">&nbsp;</td></tr>'
        f"<tr>{_CURRENT_LOGO_CELL}"
        f'<img src="{branding.logo_url}" alt="Logo {_escape_title(branding.product_name)}" width="120" />'
        "</td></tr>"
        '<tr><td style="padding: 30px 25px;">'
        f"{title_html}"
        f"{inner_html}"
        "</td></tr>"
        f'<tr><td style="background-color: {branding.action_color}; height: 4px; '
        'font-size: 0; line-height: 0;">&nbsp;</td></tr>'
        '<tr><td style="padding: 15px; text-align: center; font-size: 12px; color: #666666;">'
        f"{footer}"
        "</td></tr>"
        "</tbody></table>"
    )


def _footer_text(language: str, product_name: str) -> str:
    product = _escape_title(product_name)
    templates = {
        "fr": "Ce message est un e-mail automatique généré par la plateforme {product}.",
        "en": "This is an automated email generated by the {product} platform.",
        "de": "Dies ist eine automatisch von der Plattform {product} generierte E-Mail.",
        "es": "Este es un correo electrónico automático generado por la plataforma {product}.",
        "it": "Questa è un'e-mail automatica generata dalla piattaforma {product}.",
        "nl": "Dit is een automatisch door het platform {product} gegenereerde e-mail.",
        "pt": "Este é um e-mail automático gerado pela plataforma {product}.",
    }
    template = templates.get(
        language,
        "This is an automated email generated by the {product} platform.",
    )
    return template.format(product=product)


def apply_branding_to_existing(body: str, branding: Branding) -> str:
    """Replace known logo URLs and hard-coded palette with tenant branding."""
    if not body:
        return body
    out = body
    out = re.sub(
        r'src="https?://(?:www\.)?companieslogo\.com[^"]*"',
        f'src="{branding.logo_url}"',
        out,
        flags=re.I,
    )
    out = re.sub(
        r'src="https?://[^"]*CS\.PA[^"]*"',
        f'src="{branding.logo_url}"',
        out,
        flags=re.I,
    )
    out = re.sub(
        r'(<img\b[^>]*\balts?="[^"]*Logo[^"]*"[^>]*\bsrc=")[^"]+(")',
        rf"\1{branding.logo_url}\2",
        out,
        flags=re.I,
    )
    out = re.sub(
        r'(<img\b[^>]*\bsrc=")[^"]+("[^>]*\balts?="[^"]*Logo[^"]*")',
        rf"\1{branding.logo_url}\2",
        out,
        flags=re.I,
    )
    replacements = {
        "#01038f": branding.navigation_color,
        "#01038F": branding.navigation_color,
        "#f5111d": branding.action_color,
        "#F5111D": branding.action_color,
    }
    for old, new in replacements.items():
        out = out.replace(old, new)
    out = re.sub(
        r"plateforme Identity Security d'AXA",
        f"plateforme {_escape_title(branding.product_name)}",
        out,
        flags=re.I,
    )
    return out


def _escape_title(value: str) -> str:
    return (
        value.replace("&", "&amp;")
        .replace("<", "&lt;")
        .replace(">", "&gt;")
        .replace('"', "&quot;")
    )
